# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    environment: Nuget

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: NuGet Push
      env:
       NUGET_TOKEN: ${{ secrets.NUGETAPIKEY }}
      run: dotnet nuget push ("cli\bin\nupkg\" + (Get-ChildItem -Path "cli\bin\nupkg\*.nupkg" -Force -Recurse -File | Select-Object -First 1).Name) -k $env:NUGET_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 
      
